config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  root to: 'pages#home'
  devise_for :users

  resources :events, except: [:destroy] do
    resources :registrations, only: [:create]
  end
  resources :categories
  resources :users, only: [:show]
  resources :profiles, only: [:new, :edit, :create, :update]
  resources :photos, only: [:destroy]

  namespace :api do
    resources :events do
      resources :registrations, only: [:create]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :events

  validates :name, presence: true, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true
  has_and_belongs_to_many :categories
  has_many :photos, dependent: :destroy

  has_many :registrations, dependent: :destroy
  has_many :participants, through: :registrations, source: :user

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :starts_at, presence: true
  validates :ends_at, presence: true

end
#

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true, length: { maximum: 500}


  def full_name
    "#{first_name} #{last_name}"
  end

end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :event

def total_price
  self.price = price.event
  self.total = price * number_of_participants
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
  has_secure_token
  has_many :events, dependent: :destroy
  has_many :registrations, dependent: :destroy
  has_many :registered_events, through: :registrations, source: :event


  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

 def index
   @events = current_user.events
 end

 def show
   @categories = @event.categories
   @photos = @event.photos
 end

 def new
   @event = current_user.events.build
 end

 def create
  @event = current_user.events.build(event_params)

  if @event.save
    image_params.each do |image|
      @event.photos.create(image: image)
    end

    redirect_to edit_event_path(@event), notice: "Event  created"
  else
    render :new
  end
end


 def edit
   if current_user.id == @event.user.id
     @photos = @event.photos
   else
     redirect_to root_path, notice: "You don't have permission."
  #  @event = Event.find(params[:id])
    end
 end

 def update
   if @event.update(event_params)
     image_params.each do |image|
       @event.photos.create(image: image)
     end

     redirect_to @event, notice: "Event updated"
   else
     render :edit
   end
 end

 private

 def set_event
   @event = Event.find(params[:id])
 end

 def event_params
   params
     .require(:event)
     .permit(
       :name, :description, :location, :price, :capacity, :includes_food, :includes_drinks, :starts_at, :ends_at, :active, category_ids: []
     )
 end

  def image_params
   params[:images].present? ? params.require(:images) : []
  end
  # def image_params
  #   return params.require(:images) if params[:images].present
  #   []
  #   end
  # end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @event = photo.event
    if @event.user.id == current_user.id
      photo.destroy

      redirect_to event_path(@event), notice: "Photo successfully removed"
    else
      redirect_to @event, notice: "Cannot delete that photo"
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<br>
<hr>
<hr>
<hr> <hr>
<hr>

<hr>
<hr>
<hr>
<hr>
<hr>
<hr>
<hr>
<hr>
<hr>
<hr>
<p>Lorem Ipsum
"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit vehicula ullamcorper. Suspendisse et convallis felis. Pellentesque volutpat pulvinar venenatis. Morbi tincidunt nisi at posuere sagittis. Aenean facilisis commodo metus ut venenatis. Donec a mi sed sem scelerisque ultricies sit amet id nisi. Maecenas rhoncus arcu et ullamcorper efficitur. Etiam vitae ipsum nec ante accumsan vehicula. Cras tincidunt consectetur odio ut suscipit. In eu diam tincidunt, laoreet neque eu, gravida enim. Donec consectetur sagittis feugiat. Nam justo urna, sollicitudin quis egestas porttitor, venenatis eu ante. Praesent tempor dapibus dolor, non sollicitudin augue condimentum et. Proin facilisis eros id ipsum congue malesuada.

In pretium magna libero, eu pulvinar tortor facilisis nec. Donec ac sapien erat. Maecenas leo nisl, accumsan ut lobortis ut, faucibus euismod erat. Nullam porttitor dictum risus, sed ultrices elit lobortis vitae. Curabitur aliquet condimentum urna, at blandit lectus tincidunt sit amet. Etiam vel enim accumsan, lobortis nisl eu, dictum quam. Phasellus eu suscipit dui. Phasellus blandit augue enim, semper cursus nunc laoreet quis. Nullam pretium nunc eget dui rhoncus, at mollis dui venenatis.

Nunc erat lectus, vehicula nec neque eu, egestas auctor tortor. Sed sapien massa, consectetur non enim eu, mattis hendrerit est. Morbi vehicula arcu a mauris lacinia congue. Phasellus aliquam iaculis orci, vel varius odio vehicula eget. Nunc fermentum auctor sapien, et ultricies nulla accumsan nec. Maecenas dolor nisl, sagittis eu ligula et, convallis tincidunt arcu. Praesent ut orci at elit pharetra laoreet. Fusce fermentum, sapien a maximus pellentesque, lorem turpis volutpat felis, sed maximus justo quam et metus. Duis consequat placerat metus. Cras ut iaculis leo. Proin egestas elit eget efficitur aliquet. Integer ac enim sed eros lobortis eleifend. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas varius nunc nunc, vitae sodales magna dignissim in. Nunc ultricies est tellus, non consectetur sem sodales vel.

Mauris tincidunt risus massa. Cras quis ornare tortor. Nullam eu vulputate arcu. Phasellus mollis faucibus magna vel volutpat. Nam at lacus ut est pretium pharetra. Donec leo mi, placerat id nibh eu, porta ullamcorper nulla. Nam non vulputate eros.

Etiam quis ex nec eros pretium imperdiet. Nunc vel magna lectus. Aliquam malesuada tellus eros, sed hendrerit justo cursus in. Cras posuere vulputate sem vel tristique. Proin finibus dapibus eros tempus feugiat. Fusce posuere turpis sit amet magna gravida, ut placerat nisi dignissim. Suspendisse placerat diam eget quam condimentum, in tempor turpis varius. Suspendisse potenti. Etiam sagittis consequat massa, non sodales lacus imperdiet et. Proin sit amet aliquet nulla. Quisque eget diam ut felis vestibulum convallis. Donec a sapien non quam sollicitudin consequat quis ut libero. Phasellus ultricies ante quis purus tristique porttitor. Quisque pharetra erat sit amet lectus gravida, quis dapibus ligula maximus. Aenean eget massa in ipsum convallis convallis ac vitae nunc. Mauris efficitur tortor odio, vel dictum ex semper ac.

</p>
<hr>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurup", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>



        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">

             <%= current_user.has_profile? ? current_user.full_name : current_user.email  %> <span class="caret"></span></a>


          <ul class="dropdown-menu">
              <li><%= link_to "Your Events", events_path %></li>
              <li role="separator" class="divider"></li>
              <% if current_user.has_profile? %>
                <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
              <% else %>
                <li><%= link_to "Create Profile", new_profile_path %></li>
              <% end %>
              <li><%= link_to "Edit Password", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>              

        </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>