config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  root to: 'pages#home'
  devise_for :users

  resources :events, except: [:destroy] do
    resources :registrations, only: [:create]
  end
  resources :categories
  resources :users, only: [:show]
  resources :profiles, only: [:new, :edit, :create, :update]
  resources :photos, only: [:destroy]

  namespace :api do
    resources :events do
      resources :registrations, only: [:create]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :events

  validates :name, presence: true, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true
  has_and_belongs_to_many :categories
  has_many :photos, dependent: :destroy

  has_many :registrations, dependent: :destroy
  has_many :participants, through: :registrations, source: :user

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :starts_at, presence: true
  validates :ends_at, presence: true

end
#

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true, length: { maximum: 500}


  def full_name
    "#{first_name} #{last_name}"
  end

end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :event

def total_price
  self.price = price.event
  self.total = price * number_of_participants
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
  has_secure_token
  has_many :events, dependent: :destroy
  has_many :registrations, dependent: :destroy
  has_many :registered_events, through: :registrations, source: :event


  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end

end

app/controllers/api/events_controller.rb
class Api::EventsController < Api::BaseController



  def index
    events = Event.all
    render status: 200, json: events
  end

  def show
    event = Event.find(params[:id])
    render status: 200, json: event
  end

  def create
    event = Event.new(event_params)

    if event.save
      render status: 201, json: {
        message: "Event successfully created",
        event: event
      }.to_json
    else
      render status: 422, json: {
        errors: event.errors
      }.to_json
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy

    render status: 200, json: {
      message: "Event successfully deleted"
    }.to_json
  end

  def update
    event = Event.find(params[:id])
    if event.update(event_params)
      render status: 200, json: {
        message: "Event successfully updated",
        event: event
      }.to_json
    else
      render status: 422, json: {
        message: "Event could not be updated",
        errors: event.errors
      }.to_json
    end
  end



  private

  def event_params
    params
    .require(:event)
    .permit(:name, :description, :location, :price, :capacity, :includes_food, :includes_drinks, :starts_at, :ends_at, :active, categories: [])

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

 def index
   @events = current_user.events
 end

 def show
   @categories = @event.categories
   @photos = @event.photos
 end

 def new
   @event = current_user.events.build
 end

 def create
  @event = current_user.events.build(event_params)

  if @event.save
    image_params.each do |image|
      @event.photos.create(image: image)
    end

    redirect_to edit_event_path(@event), notice: "Event  created"
  else
    render :new
  end
end


 def edit
   if current_user.id == @event.user.id
     @photos = @event.photos
   else
     redirect_to root_path, notice: "You don't have permission."
  #  @event = Event.find(params[:id])
    end
 end

 def update
   if @event.update(event_params)
     image_params.each do |image|
       @event.photos.create(image: image)
     end

     redirect_to @event, notice: "Event updated"
   else
     render :edit
   end
 end

 private

 def set_event
   @event = Event.find(params[:id])
 end

 def event_params
   params
     .require(:event)
     .permit(
       :name, :description, :location, :price, :capacity, :includes_food, :includes_drinks, :starts_at, :ends_at, :active, category_ids: []
     )
 end

  def image_params
   params[:images].present? ? params.require(:images) : []
  end
  # def image_params
  #   return params.require(:images) if params[:images].present
  #   []
  #   end
  # end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @event = photo.event
    if @event.user.id == current_user.id
      photo.destroy

      redirect_to event_path(@event), notice: "Photo successfully removed"
    else
      redirect_to @event, notice: "Cannot delete that photo"
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio)
    end


end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
before_action :authenticate_user!

  def create
      @registration = current_user.registration.create(registration_params)

      redirect_to @registration.event, notice: "thank you for your registration"
  end

  private
  def registration_params
    params
    .require(:registration)
    .permit(:price, :guest_count, :price, :total, :event_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>
<% @event.errors.full_messages.each do |msg| %>
  <p class="alert alert-danger"><%= msg %></p>
<% end %>

  <div class="form-group">
    <label>Name</label>
    <%= f.text_field :name, placeholder: "What name would best describe your event", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Description</label>
    <%= f.text_area :description, rows: 5, placeholder: "Tell us more about your event", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Location</label>
    <%= f.text_field :location, placeholder: "Where is the event taking place", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Number of maximum participants</label>
    <%= f.number_field :capacity, placeholder: "How many people can join", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Price</label>
    <div class="input-group">
      <div class="input-group-addon">€</div>
      <%= f.number_field :price, placeholder: "e.g. 5.50", class: "form-control" %>
    </div>
  </div>

  <label>Tick if it includes the following</label>

  <div class="form-group">
    <%= f.check_box :includes_food %> Food
  </div>

  <div class="form-group">
    <%= f.check_box :includes_drinks %> Drinks
  </div>

  <div class="form-group">
    <label>Start time</label>
    <%= f.datetime_select :starts_at, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>End time</label>
    <%= f.datetime_select :ends_at, class: "form-control" %>
  </div>

  <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b|%>
  <div class="form-group">
    <%= b.check_box(class: "check_box") %>
    <%= b.object.name %>
  </div>
  <% end %>

  <label>Photos</label>

  <div id="photos">
    <%= render 'photos/list' %>
  </div>

  <div class="form-group">
    <span class="btn btn-default">
      Upload Photos
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </span>
  </div>


  <label>Publish this place?</label>

   <div class="form-group">
     <%= f.check_box :active %> Make public
   </div>


  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>


<% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Events", events_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Participants", events_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Events
      </div>
      <div class="panel-body">

        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= event.name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Edit", edit_event_path(event), class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new event", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new Event
  </div>

<%
=begin %>
  <% if @event.errors? %>
  <ul>
    <% @event.errors.each do |error| %>
    <li><%= error.full_messages %></li>
    <% end %>
  </ul>
  <% end %>
<% 
=end %>



  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<!-- Booking Form -->
<% if current_user != @event.user %>
  <div class="panel panel-primary">
    <div class="panel-heading">Register for this event!</div>

    <div class="panel-body">
      <%= render 'registrations/form' %>
    </div>
  </div>
<% end %>



<div class="panel panel-primary">
  <div class="panel-heading"><%= @event.name %></div>

  <div class="panel-body">

    <p>City: <%= @event.location %></p>
    <p>Host: <%= @event.user.email %></p>

    <!-- Main Info -->
    <h4>Main Info</h4>
    <p>Activity: <%= @event.name %></p>
    <p>Start date and time: &nbsp &nbsp <%= @event.starts_at %> hours</p>
    <p>End date and time: &nbsp &nbsp <%= @event.ends_at %> hours</p>
    <p>Maximum number of people: &nbsp <%= @event.capacity %></p>


    <!-- About -->
    <h4>About</h4>
    <p><%= @event.description %></p>

    <!-- Amenities -->
    <h4>Details</h4>
    <ul class="amenities">
      <li><%= !@event.includes_food ? ("<s>Food</s>").html_safe : "Food" %></li>
      <li><%= !@event.includes_drinks ? ("<del>Drinks</del>").html_safe : "Drinks" %></li>
    </ul>

    <h4>Categories</h4>
    <% @categories.each do |category| %>
    <span class="label-success"> <%= category.name %></span>
    <% end %>

    <h4>Price: <%= @event.price %></h4>

    <h4>Photos</h4>
    <div class="row">
      <% @event.photos.each do |photo| %>
      <div class="col-md-4">
      <%= image_tag photo.image.thumbnail %>
      </div>
      <% end %>
    </div>


    <h4>Public?</h4>
      <p><%= @event.active ? "Published" : "Private" %></p>

    <%= link_to "Edit", edit_event_path, class: "btn btn-primary" %>

  </div>
</div>

<%= link_to "Back", events_path, class: "btn btn-default" %>